{{- if not .Values.env.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remotecache.fullname" . }}
  labels:
    {{- include "remotecache.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $name, $value := .Values.env.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
