apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName | default (include "remotecache.fullname" .) }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "remotecache.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.service.externalPort }}
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{.Values.service.nodePort}}
    {{- else }}
    targetPort: http
    {{- end }}
    protocol: TCP
    name: http
  selector:
    {{- include "remotecache.selectorLabels" . | nindent 4 }}